name: Tests

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - env:
                  TEST_DATABASE_URI: ${{ secrets.TEST_DATABASE_URI }}
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'yarn'
            - name: Install modules
              run: yarn install
            - name: Run tests (using Jest)
              run: yarn test
